#!/usr/bin/python -OOtt
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Thu Jun 11 15:37:13 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Trader(QtGui.QWidget):
    def setupUi(self, Trader):
        Trader.setObjectName(_fromUtf8("Trader"))
        Trader.resize(730, 262)
        self.verticalLayout_2 = QtGui.QVBoxLayout(Trader)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.tabWidget = QtGui.QTabWidget(Trader)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.tabWidget.setFont(font)
        self.tabWidget.setToolTip(_fromUtf8(""))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_trade = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_trade.sizePolicy().hasHeightForWidth())
        self.tab_trade.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tab_trade.setFont(font)
        self.tab_trade.setObjectName(_fromUtf8("tab_trade"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tab_trade)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.verticalLayout_trade = QtGui.QVBoxLayout()
        self.verticalLayout_trade.setObjectName(_fromUtf8("verticalLayout_trade"))
        self.horizontalLayout_trade_1 = QtGui.QHBoxLayout()
        self.horizontalLayout_trade_1.setObjectName(_fromUtf8("horizontalLayout_trade_1"))
        self.checkBox_buy = QtGui.QCheckBox(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_buy.sizePolicy().hasHeightForWidth())
        self.checkBox_buy.setSizePolicy(sizePolicy)
        self.checkBox_buy.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_buy.setFont(font)
        self.checkBox_buy.setObjectName(_fromUtf8("checkBox_buy"))
        self.horizontalLayout_trade_1.addWidget(self.checkBox_buy)
        self.checkBox_sell = QtGui.QCheckBox(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.checkBox_sell.sizePolicy().hasHeightForWidth())
        self.checkBox_sell.setSizePolicy(sizePolicy)
        self.checkBox_sell.setMaximumSize(QtCore.QSize(54, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.checkBox_sell.setFont(font)
        self.checkBox_sell.setObjectName(_fromUtf8("checkBox_sell"))
        self.horizontalLayout_trade_1.addWidget(self.checkBox_sell)
        self.label_type = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_type.sizePolicy().hasHeightForWidth())
        self.label_type.setSizePolicy(sizePolicy)
        self.label_type.setMaximumSize(QtCore.QSize(95, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_type.setFont(font)
        self.label_type.setIndent(20)
        self.label_type.setObjectName(_fromUtf8("label_type"))
        self.horizontalLayout_trade_1.addWidget(self.label_type)
        self.label_value = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_value.sizePolicy().hasHeightForWidth())
        self.label_value.setSizePolicy(sizePolicy)
        self.label_value.setMaximumSize(QtCore.QSize(500, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_value.setFont(font)
        self.label_value.setAlignment(QtCore.Qt.AlignCenter)
        self.label_value.setObjectName(_fromUtf8("label_value"))
        self.horizontalLayout_trade_1.addWidget(self.label_value)
        self.label_percent = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_percent.sizePolicy().hasHeightForWidth())
        self.label_percent.setSizePolicy(sizePolicy)
        self.label_percent.setMaximumSize(QtCore.QSize(180, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_percent.setFont(font)
        self.label_percent.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_percent.setObjectName(_fromUtf8("label_percent"))
        self.horizontalLayout_trade_1.addWidget(self.label_percent)
        self.label_pixmap = QtGui.QLabel(self.tab_trade)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_pixmap.setFont(font)
        self.label_pixmap.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pixmap.setObjectName(_fromUtf8("label_pixmap"))
        self.horizontalLayout_trade_1.addWidget(self.label_pixmap)
        self.verticalLayout_trade.addLayout(self.horizontalLayout_trade_1)
        self.horizontalLayout_trade_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_trade_2.setObjectName(_fromUtf8("horizontalLayout_trade_2"))
        self.label_export_sell = QtGui.QLabel(self.tab_trade)
        self.label_export_sell.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        self.label_export_sell.setFont(font)
        self.label_export_sell.setObjectName(_fromUtf8("label_export_sell"))
        self.horizontalLayout_trade_2.addWidget(self.label_export_sell)
        self.label_export_buy = QtGui.QLabel(self.tab_trade)
        self.label_export_buy.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        self.label_export_buy.setFont(font)
        self.label_export_buy.setObjectName(_fromUtf8("label_export_buy"))
        self.horizontalLayout_trade_2.addWidget(self.label_export_buy)
        self.label_export_diff = QtGui.QLabel(self.tab_trade)
        self.label_export_diff.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_export_diff.setFont(font)
        self.label_export_diff.setObjectName(_fromUtf8("label_export_diff"))
        self.horizontalLayout_trade_2.addWidget(self.label_export_diff)
        self.label_export_percent = QtGui.QLabel(self.tab_trade)
        self.label_export_percent.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.label_export_percent.setFont(font)
        self.label_export_percent.setObjectName(_fromUtf8("label_export_percent"))
        self.horizontalLayout_trade_2.addWidget(self.label_export_percent)
        self.label_item = QtGui.QLabel(self.tab_trade)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_item.setFont(font)
        self.label_item.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_item.setObjectName(_fromUtf8("label_item"))
        self.horizontalLayout_trade_2.addWidget(self.label_item)
        self.combo_manual = QtGui.QComboBox(self.tab_trade)
        self.combo_manual.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.combo_manual.sizePolicy().hasHeightForWidth())
        self.combo_manual.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(8)
        self.combo_manual.setFont(font)
        self.combo_manual.setMaxVisibleItems(42)
        self.combo_manual.setObjectName(_fromUtf8("combo_manual"))
        self.horizontalLayout_trade_2.addWidget(self.combo_manual)
        self.button_manual = QtGui.QPushButton(self.tab_trade)
        self.button_manual.setMaximumSize(QtCore.QSize(20, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.button_manual.setFont(font)
        self.button_manual.setObjectName(_fromUtf8("button_manual"))
        self.horizontalLayout_trade_2.addWidget(self.button_manual)
        self.verticalLayout_trade.addLayout(self.horizontalLayout_trade_2)
        self.gridLayout_trade_market = QtGui.QGridLayout()
        self.gridLayout_trade_market.setContentsMargins(-1, 3, -1, -1)
        self.gridLayout_trade_market.setObjectName(_fromUtf8("gridLayout_trade_market"))
        self.label_m_buy_low_icon = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_buy_low_icon.sizePolicy().hasHeightForWidth())
        self.label_m_buy_low_icon.setSizePolicy(sizePolicy)
        self.label_m_buy_low_icon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_m_buy_low_icon.setText(_fromUtf8(""))
        self.label_m_buy_low_icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_m_buy_low_icon.setObjectName(_fromUtf8("label_m_buy_low_icon"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_low_icon, 1, 2, 1, 1)
        self.label_m_sell_low_icon = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_sell_low_icon.sizePolicy().hasHeightForWidth())
        self.label_m_sell_low_icon.setSizePolicy(sizePolicy)
        self.label_m_sell_low_icon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_m_sell_low_icon.setText(_fromUtf8(""))
        self.label_m_sell_low_icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_m_sell_low_icon.setObjectName(_fromUtf8("label_m_sell_low_icon"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_low_icon, 0, 2, 1, 1)
        self.label_m_sell_high_percent = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_sell_high_percent.sizePolicy().hasHeightForWidth())
        self.label_m_sell_high_percent.setSizePolicy(sizePolicy)
        self.label_m_sell_high_percent.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_sell_high_percent.setFont(font)
        self.label_m_sell_high_percent.setObjectName(_fromUtf8("label_m_sell_high_percent"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_high_percent, 0, 6, 1, 1)
        self.label_m_buy_fixed = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_buy_fixed.sizePolicy().hasHeightForWidth())
        self.label_m_buy_fixed.setSizePolicy(sizePolicy)
        self.label_m_buy_fixed.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        self.label_m_buy_fixed.setFont(font)
        self.label_m_buy_fixed.setObjectName(_fromUtf8("label_m_buy_fixed"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_fixed, 1, 0, 1, 1)
        self.label_m_buy_high = QtGui.QLabel(self.tab_trade)
        self.label_m_buy_high.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_buy_high.setFont(font)
        self.label_m_buy_high.setObjectName(_fromUtf8("label_m_buy_high"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_high, 1, 4, 1, 1)
        self.label_m_buy_low = QtGui.QLabel(self.tab_trade)
        self.label_m_buy_low.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_buy_low.setFont(font)
        self.label_m_buy_low.setObjectName(_fromUtf8("label_m_buy_low"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_low, 1, 1, 1, 1)
        self.label_m_sell_high = QtGui.QLabel(self.tab_trade)
        self.label_m_sell_high.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_sell_high.setFont(font)
        self.label_m_sell_high.setObjectName(_fromUtf8("label_m_sell_high"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_high, 0, 4, 1, 1)
        self.label_m_buy_high_percent = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_buy_high_percent.sizePolicy().hasHeightForWidth())
        self.label_m_buy_high_percent.setSizePolicy(sizePolicy)
        self.label_m_buy_high_percent.setMaximumSize(QtCore.QSize(110, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_buy_high_percent.setFont(font)
        self.label_m_buy_high_percent.setObjectName(_fromUtf8("label_m_buy_high_percent"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_high_percent, 1, 6, 1, 1)
        self.label_m_sell_low = QtGui.QLabel(self.tab_trade)
        self.label_m_sell_low.setMaximumSize(QtCore.QSize(300, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_sell_low.setFont(font)
        self.label_m_sell_low.setObjectName(_fromUtf8("label_m_sell_low"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_low, 0, 1, 1, 1)
        self.label_m_sell_fixed = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_sell_fixed.sizePolicy().hasHeightForWidth())
        self.label_m_sell_fixed.setSizePolicy(sizePolicy)
        self.label_m_sell_fixed.setMaximumSize(QtCore.QSize(35, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        self.label_m_sell_fixed.setFont(font)
        self.label_m_sell_fixed.setObjectName(_fromUtf8("label_m_sell_fixed"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_fixed, 0, 0, 1, 1)
        self.label_m_sell_low_percent = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_sell_low_percent.sizePolicy().hasHeightForWidth())
        self.label_m_sell_low_percent.setSizePolicy(sizePolicy)
        self.label_m_sell_low_percent.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_sell_low_percent.setFont(font)
        self.label_m_sell_low_percent.setObjectName(_fromUtf8("label_m_sell_low_percent"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_low_percent, 0, 3, 1, 1)
        self.label_m_buy_low_percent = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_buy_low_percent.sizePolicy().hasHeightForWidth())
        self.label_m_buy_low_percent.setSizePolicy(sizePolicy)
        self.label_m_buy_low_percent.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Mono"))
        font.setPointSize(14)
        self.label_m_buy_low_percent.setFont(font)
        self.label_m_buy_low_percent.setObjectName(_fromUtf8("label_m_buy_low_percent"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_low_percent, 1, 3, 1, 1)
        self.label_m_sell_high_icon = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_sell_high_icon.sizePolicy().hasHeightForWidth())
        self.label_m_sell_high_icon.setSizePolicy(sizePolicy)
        self.label_m_sell_high_icon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_m_sell_high_icon.setText(_fromUtf8(""))
        self.label_m_sell_high_icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_m_sell_high_icon.setObjectName(_fromUtf8("label_m_sell_high_icon"))
        self.gridLayout_trade_market.addWidget(self.label_m_sell_high_icon, 0, 5, 1, 1)
        self.label_m_buy_high_icon = QtGui.QLabel(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_m_buy_high_icon.sizePolicy().hasHeightForWidth())
        self.label_m_buy_high_icon.setSizePolicy(sizePolicy)
        self.label_m_buy_high_icon.setMaximumSize(QtCore.QSize(50, 16777215))
        self.label_m_buy_high_icon.setText(_fromUtf8(""))
        self.label_m_buy_high_icon.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_m_buy_high_icon.setObjectName(_fromUtf8("label_m_buy_high_icon"))
        self.gridLayout_trade_market.addWidget(self.label_m_buy_high_icon, 1, 5, 1, 1)
        self.verticalLayout_trade.addLayout(self.gridLayout_trade_market)
        self.gridLayout_trade_listView = QtGui.QGridLayout()
        self.gridLayout_trade_listView.setObjectName(_fromUtf8("gridLayout_trade_listView"))
        self.listView = QtGui.QListView(self.tab_trade)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listView.sizePolicy().hasHeightForWidth())
        self.listView.setSizePolicy(sizePolicy)
        self.listView.setMaximumSize(QtCore.QSize(16777215, 60))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.listView.setFont(font)
        self.listView.setObjectName(_fromUtf8("listView"))
        self.gridLayout_trade_listView.addWidget(self.listView, 0, 0, 1, 1)
        self.verticalLayout_trade.addLayout(self.gridLayout_trade_listView)
        self.verticalLayout_3.addLayout(self.verticalLayout_trade)
        self.tabWidget.addTab(self.tab_trade, _fromUtf8(""))
        self.tab_calc = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_calc.sizePolicy().hasHeightForWidth())
        self.tab_calc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setBold(True)
        font.setWeight(75)
        self.tab_calc.setFont(font)
        self.tab_calc.setObjectName(_fromUtf8("tab_calc"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_calc)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.frame_calc = QtGui.QFrame(self.tab_calc)
        self.frame_calc.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_calc.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_calc.setObjectName(_fromUtf8("frame_calc"))
        self.layoutWidget = QtGui.QWidget(self.frame_calc)
        self.layoutWidget.setGeometry(QtCore.QRect(120, 0, 466, 201))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.verticalLayout_calc = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_calc.setMargin(0)
        self.verticalLayout_calc.setObjectName(_fromUtf8("verticalLayout_calc"))
        self.horizontalLayout_calc_lineEdit = QtGui.QHBoxLayout()
        self.horizontalLayout_calc_lineEdit.setSpacing(1)
        self.horizontalLayout_calc_lineEdit.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_calc_lineEdit.setObjectName(_fromUtf8("horizontalLayout_calc_lineEdit"))
        self.lineEdit = QtGui.QLineEdit(self.layoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setMinimumSize(QtCore.QSize(444, 33))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName(_fromUtf8("lineEdit"))
        self.horizontalLayout_calc_lineEdit.addWidget(self.lineEdit)
        self.verticalLayout_calc.addLayout(self.horizontalLayout_calc_lineEdit)
        self.horizontalLayout_calc_789 = QtGui.QHBoxLayout()
        self.horizontalLayout_calc_789.setSpacing(1)
        self.horizontalLayout_calc_789.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_calc_789.setObjectName(_fromUtf8("horizontalLayout_calc_789"))
        self.pushButton_7 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_7.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_7.setFont(font)
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.horizontalLayout_calc_789.addWidget(self.pushButton_7)
        self.pushButton_8 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_8.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_8.setFont(font)
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.horizontalLayout_calc_789.addWidget(self.pushButton_8)
        self.pushButton_9 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_9.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_9.setFont(font)
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.horizontalLayout_calc_789.addWidget(self.pushButton_9)
        self.pushButton_divide = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_divide.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_divide.setFont(font)
        self.pushButton_divide.setObjectName(_fromUtf8("pushButton_divide"))
        self.horizontalLayout_calc_789.addWidget(self.pushButton_divide)
        self.pushButton_000 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_000.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_000.setFont(font)
        self.pushButton_000.setObjectName(_fromUtf8("pushButton_000"))
        self.horizontalLayout_calc_789.addWidget(self.pushButton_000)
        self.verticalLayout_calc.addLayout(self.horizontalLayout_calc_789)
        self.horizontalLayout_calc_456 = QtGui.QHBoxLayout()
        self.horizontalLayout_calc_456.setSpacing(1)
        self.horizontalLayout_calc_456.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_calc_456.setObjectName(_fromUtf8("horizontalLayout_calc_456"))
        self.pushButton_4 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_4.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.horizontalLayout_calc_456.addWidget(self.pushButton_4)
        self.pushButton_5 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_5.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.horizontalLayout_calc_456.addWidget(self.pushButton_5)
        self.pushButton_6 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_6.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_6.setFont(font)
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.horizontalLayout_calc_456.addWidget(self.pushButton_6)
        self.pushButton_x = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_x.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_x.setFont(font)
        self.pushButton_x.setObjectName(_fromUtf8("pushButton_x"))
        self.horizontalLayout_calc_456.addWidget(self.pushButton_x)
        self.pushButton_99 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_99.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_99.setFont(font)
        self.pushButton_99.setObjectName(_fromUtf8("pushButton_99"))
        self.horizontalLayout_calc_456.addWidget(self.pushButton_99)
        self.verticalLayout_calc.addLayout(self.horizontalLayout_calc_456)
        self.horizontalLayout_calc_123 = QtGui.QHBoxLayout()
        self.horizontalLayout_calc_123.setSpacing(1)
        self.horizontalLayout_calc_123.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_calc_123.setObjectName(_fromUtf8("horizontalLayout_calc_123"))
        self.pushButton_1 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_1.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName(_fromUtf8("pushButton_1"))
        self.horizontalLayout_calc_123.addWidget(self.pushButton_1)
        self.pushButton_2 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_2.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.horizontalLayout_calc_123.addWidget(self.pushButton_2)
        self.pushButton_3 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_3.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.horizontalLayout_calc_123.addWidget(self.pushButton_3)
        self.pushButton_minus = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_minus.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_minus.setFont(font)
        self.pushButton_minus.setObjectName(_fromUtf8("pushButton_minus"))
        self.horizontalLayout_calc_123.addWidget(self.pushButton_minus)
        self.pushButton_01 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_01.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_01.setFont(font)
        self.pushButton_01.setObjectName(_fromUtf8("pushButton_01"))
        self.horizontalLayout_calc_123.addWidget(self.pushButton_01)
        self.verticalLayout_calc.addLayout(self.horizontalLayout_calc_123)
        self.horizontalLayout_calc_0 = QtGui.QHBoxLayout()
        self.horizontalLayout_calc_0.setSpacing(1)
        self.horizontalLayout_calc_0.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_calc_0.setObjectName(_fromUtf8("horizontalLayout_calc_0"))
        self.pushButton_0 = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_0.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_0.setFont(font)
        self.pushButton_0.setObjectName(_fromUtf8("pushButton_0"))
        self.horizontalLayout_calc_0.addWidget(self.pushButton_0)
        self.pushButton_dot = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_dot.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_dot.setFont(font)
        self.pushButton_dot.setObjectName(_fromUtf8("pushButton_dot"))
        self.horizontalLayout_calc_0.addWidget(self.pushButton_dot)
        self.pushButton_equal = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_equal.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_equal.setFont(font)
        self.pushButton_equal.setObjectName(_fromUtf8("pushButton_equal"))
        self.horizontalLayout_calc_0.addWidget(self.pushButton_equal)
        self.pushButton_plus = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_plus.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_plus.setFont(font)
        self.pushButton_plus.setObjectName(_fromUtf8("pushButton_plus"))
        self.horizontalLayout_calc_0.addWidget(self.pushButton_plus)
        self.pushButton_C = QtGui.QPushButton(self.layoutWidget)
        self.pushButton_C.setMaximumSize(QtCore.QSize(80, 28))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_C.setFont(font)
        self.pushButton_C.setObjectName(_fromUtf8("pushButton_C"))
        self.horizontalLayout_calc_0.addWidget(self.pushButton_C)
        self.verticalLayout_calc.addLayout(self.horizontalLayout_calc_0)
        self.gridLayout_3.addWidget(self.frame_calc, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_calc, _fromUtf8(""))
        self.tab_indy = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_indy.sizePolicy().hasHeightForWidth())
        self.tab_indy.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setBold(True)
        font.setWeight(75)
        self.tab_indy.setFont(font)
        self.tab_indy.setObjectName(_fromUtf8("tab_indy"))
        self.frame_indy = QtGui.QFrame(self.tab_indy)
        self.frame_indy.setGeometry(QtCore.QRect(4, 4, 711, 211))
        self.frame_indy.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_indy.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_indy.setObjectName(_fromUtf8("frame_indy"))
        self.combo_blueprint = QtGui.QComboBox(self.frame_indy)
        self.combo_blueprint.setGeometry(QtCore.QRect(100, 10, 381, 22))
        self.combo_blueprint.setObjectName(_fromUtf8("combo_blueprint"))
        self.label_blueprint = QtGui.QLabel(self.frame_indy)
        self.label_blueprint.setGeometry(QtCore.QRect(9, 10, 91, 21))
        self.label_blueprint.setObjectName(_fromUtf8("label_blueprint"))
        self.table_blueprint = QtGui.QTableWidget(self.frame_indy)
        self.table_blueprint.setGeometry(QtCore.QRect(0, 40, 701, 171))
        self.table_blueprint.setObjectName(_fromUtf8("table_blueprint"))
        self.table_blueprint.setColumnCount(0)
        self.table_blueprint.setRowCount(0)
        self.label_cost = QtGui.QLabel(self.frame_indy)
        self.label_cost.setGeometry(QtCore.QRect(490, 10, 31, 21))
        self.label_cost.setObjectName(_fromUtf8("label_cost"))
        self.label_cost_actual = QtGui.QLabel(self.frame_indy)
        self.label_cost_actual.setGeometry(QtCore.QRect(530, 10, 161, 21))
        self.label_cost_actual.setObjectName(_fromUtf8("label_cost_actual"))
        self.tabWidget.addTab(self.tab_indy, _fromUtf8(""))
        self.tab_info = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_info.sizePolicy().hasHeightForWidth())
        self.tab_info.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setBold(True)
        font.setWeight(75)
        self.tab_info.setFont(font)
        self.tab_info.setObjectName(_fromUtf8("tab_info"))
        self.frame_info = QtGui.QFrame(self.tab_info)
        self.frame_info.setGeometry(QtCore.QRect(4, 4, 711, 187))
        self.frame_info.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_info.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_info.setObjectName(_fromUtf8("frame_info"))
        self.label_copyright = QtGui.QLabel(self.frame_info)
        self.label_copyright.setGeometry(QtCore.QRect(10, 0, 711, 181))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.label_copyright.setFont(font)
        self.label_copyright.setObjectName(_fromUtf8("label_copyright"))
        self.tabWidget.addTab(self.tab_info, _fromUtf8(""))
        self.tab_pref = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_pref.sizePolicy().hasHeightForWidth())
        self.tab_pref.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setBold(True)
        font.setWeight(75)
        self.tab_pref.setFont(font)
        self.tab_pref.setObjectName(_fromUtf8("tab_pref"))
        self.gridLayout_pref = QtGui.QGridLayout(self.tab_pref)
        self.gridLayout_pref.setObjectName(_fromUtf8("gridLayout_pref"))
        self.frame_pref = QtGui.QFrame(self.tab_pref)
        self.frame_pref.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_pref.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_pref.setObjectName(_fromUtf8("frame_pref"))
        self.layoutWidget1 = QtGui.QWidget(self.frame_pref)
        self.layoutWidget1.setGeometry(QtCore.QRect(0, 10, 722, 171))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_trade_green = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_trade_green.sizePolicy().hasHeightForWidth())
        self.label_trade_green.setSizePolicy(sizePolicy)
        self.label_trade_green.setMinimumSize(QtCore.QSize(150, 0))
        self.label_trade_green.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_trade_green.setObjectName(_fromUtf8("label_trade_green"))
        self.horizontalLayout_2.addWidget(self.label_trade_green)
        self.spin_trade_green = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_trade_green.sizePolicy().hasHeightForWidth())
        self.spin_trade_green.setSizePolicy(sizePolicy)
        self.spin_trade_green.setMaximumSize(QtCore.QSize(77, 16777215))
        self.spin_trade_green.setObjectName(_fromUtf8("spin_trade_green"))
        self.horizontalLayout_2.addWidget(self.spin_trade_green)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_export_green = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_export_green.sizePolicy().hasHeightForWidth())
        self.label_export_green.setSizePolicy(sizePolicy)
        self.label_export_green.setMinimumSize(QtCore.QSize(150, 0))
        self.label_export_green.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_export_green.setObjectName(_fromUtf8("label_export_green"))
        self.horizontalLayout_5.addWidget(self.label_export_green)
        self.spin_export_green = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_export_green.sizePolicy().hasHeightForWidth())
        self.spin_export_green.setSizePolicy(sizePolicy)
        self.spin_export_green.setMaximumSize(QtCore.QSize(77, 16777215))
        self.spin_export_green.setObjectName(_fromUtf8("spin_export_green"))
        self.horizontalLayout_5.addWidget(self.spin_export_green)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_trade_yellow = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_trade_yellow.sizePolicy().hasHeightForWidth())
        self.label_trade_yellow.setSizePolicy(sizePolicy)
        self.label_trade_yellow.setMinimumSize(QtCore.QSize(150, 0))
        self.label_trade_yellow.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_trade_yellow.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_trade_yellow.setObjectName(_fromUtf8("label_trade_yellow"))
        self.horizontalLayout_3.addWidget(self.label_trade_yellow)
        self.spin_trade_yellow = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_trade_yellow.sizePolicy().hasHeightForWidth())
        self.spin_trade_yellow.setSizePolicy(sizePolicy)
        self.spin_trade_yellow.setMaximumSize(QtCore.QSize(77, 16777215))
        self.spin_trade_yellow.setObjectName(_fromUtf8("spin_trade_yellow"))
        self.horizontalLayout_3.addWidget(self.spin_trade_yellow)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_export_yellow = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_export_yellow.sizePolicy().hasHeightForWidth())
        self.label_export_yellow.setSizePolicy(sizePolicy)
        self.label_export_yellow.setMinimumSize(QtCore.QSize(150, 0))
        self.label_export_yellow.setMaximumSize(QtCore.QSize(150, 16777215))
        self.label_export_yellow.setObjectName(_fromUtf8("label_export_yellow"))
        self.horizontalLayout_6.addWidget(self.label_export_yellow)
        self.spin_export_yellow = QtGui.QDoubleSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_export_yellow.sizePolicy().hasHeightForWidth())
        self.spin_export_yellow.setSizePolicy(sizePolicy)
        self.spin_export_yellow.setMaximumSize(QtCore.QSize(77, 16777215))
        self.spin_export_yellow.setObjectName(_fromUtf8("spin_export_yellow"))
        self.horizontalLayout_6.addWidget(self.spin_export_yellow)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_export_path = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_export_path.sizePolicy().hasHeightForWidth())
        self.label_export_path.setSizePolicy(sizePolicy)
        self.label_export_path.setMinimumSize(QtCore.QSize(75, 0))
        self.label_export_path.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_export_path.setObjectName(_fromUtf8("label_export_path"))
        self.horizontalLayout_4.addWidget(self.label_export_path)
        self.lineEdit_pref_export_path = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pref_export_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_pref_export_path.setSizePolicy(sizePolicy)
        self.lineEdit_pref_export_path.setMinimumSize(QtCore.QSize(350, 0))
        self.lineEdit_pref_export_path.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_pref_export_path.setObjectName(_fromUtf8("lineEdit_pref_export_path"))
        self.horizontalLayout_4.addWidget(self.lineEdit_pref_export_path)
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_api_ttl = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_api_ttl.sizePolicy().hasHeightForWidth())
        self.label_api_ttl.setSizePolicy(sizePolicy)
        self.label_api_ttl.setMaximumSize(QtCore.QSize(60, 16777215))
        self.label_api_ttl.setObjectName(_fromUtf8("label_api_ttl"))
        self.horizontalLayout_7.addWidget(self.label_api_ttl)
        self.spin_api_ttl = QtGui.QSpinBox(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spin_api_ttl.sizePolicy().hasHeightForWidth())
        self.spin_api_ttl.setSizePolicy(sizePolicy)
        self.spin_api_ttl.setMaximumSize(QtCore.QSize(90, 16777215))
        self.spin_api_ttl.setObjectName(_fromUtf8("spin_api_ttl"))
        self.horizontalLayout_7.addWidget(self.spin_api_ttl)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout_4.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.label_save_path = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_save_path.sizePolicy().hasHeightForWidth())
        self.label_save_path.setSizePolicy(sizePolicy)
        self.label_save_path.setMinimumSize(QtCore.QSize(75, 0))
        self.label_save_path.setMaximumSize(QtCore.QSize(75, 16777215))
        self.label_save_path.setObjectName(_fromUtf8("label_save_path"))
        self.horizontalLayout_10.addWidget(self.label_save_path)
        self.lineEdit_pref_file_path = QtGui.QLineEdit(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_pref_file_path.sizePolicy().hasHeightForWidth())
        self.lineEdit_pref_file_path.setSizePolicy(sizePolicy)
        self.lineEdit_pref_file_path.setMinimumSize(QtCore.QSize(350, 0))
        self.lineEdit_pref_file_path.setMaximumSize(QtCore.QSize(400, 16777215))
        self.lineEdit_pref_file_path.setObjectName(_fromUtf8("lineEdit_pref_file_path"))
        self.horizontalLayout_10.addWidget(self.lineEdit_pref_file_path)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_pref_cached_static = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pref_cached_static.sizePolicy().hasHeightForWidth())
        self.label_pref_cached_static.setSizePolicy(sizePolicy)
        self.label_pref_cached_static.setMaximumSize(QtCore.QSize(50, 16777215))
        font = QtGui.QFont()
        font.setPointSize(7)
        font.setBold(False)
        font.setWeight(50)
        self.label_pref_cached_static.setFont(font)
        self.label_pref_cached_static.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_pref_cached_static.setObjectName(_fromUtf8("label_pref_cached_static"))
        self.horizontalLayout_8.addWidget(self.label_pref_cached_static)
        self.label_pref_cached = QtGui.QLabel(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_pref_cached.sizePolicy().hasHeightForWidth())
        self.label_pref_cached.setSizePolicy(sizePolicy)
        self.label_pref_cached.setMaximumSize(QtCore.QSize(110, 16777215))
        self.label_pref_cached.setAlignment(QtCore.Qt.AlignCenter)
        self.label_pref_cached.setObjectName(_fromUtf8("label_pref_cached"))
        self.horizontalLayout_8.addWidget(self.label_pref_cached)
        self.pushButton_pref_clear = QtGui.QPushButton(self.layoutWidget1)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pref_clear.sizePolicy().hasHeightForWidth())
        self.pushButton_pref_clear.setSizePolicy(sizePolicy)
        self.pushButton_pref_clear.setMaximumSize(QtCore.QSize(60, 16777215))
        self.pushButton_pref_clear.setObjectName(_fromUtf8("pushButton_pref_clear"))
        self.horizontalLayout_8.addWidget(self.pushButton_pref_clear)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_8)
        self.gridLayout_4.addLayout(self.horizontalLayout_10, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout_4, 3, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(5, 12, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(45, 1, QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.pushButton_pref_save = QtGui.QPushButton(self.layoutWidget1)
        self.pushButton_pref_save.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_pref_save.sizePolicy().hasHeightForWidth())
        self.pushButton_pref_save.setSizePolicy(sizePolicy)
        self.pushButton_pref_save.setMaximumSize(QtCore.QSize(95, 25))
        self.pushButton_pref_save.setObjectName(_fromUtf8("pushButton_pref_save"))
        self.horizontalLayout.addWidget(self.pushButton_pref_save)
        spacerItem2 = QtGui.QSpacerItem(40, 1, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem2)
        self.gridLayout_2.addLayout(self.horizontalLayout, 4, 0, 1, 1)
        self.gridLayout_pref.addWidget(self.frame_pref, 0, 0, 2, 1)
        self.tabWidget.addTab(self.tab_pref, _fromUtf8(""))
        self.tab_setup = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tab_setup.sizePolicy().hasHeightForWidth())
        self.tab_setup.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Liberation Narrow"))
        font.setBold(True)
        font.setWeight(75)
        self.tab_setup.setFont(font)
        self.tab_setup.setObjectName(_fromUtf8("tab_setup"))
        self.gridLayout_setup = QtGui.QGridLayout(self.tab_setup)
        self.gridLayout_setup.setObjectName(_fromUtf8("gridLayout_setup"))
        self.frame_setup = QtGui.QFrame(self.tab_setup)
        self.frame_setup.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_setup.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_setup.setObjectName(_fromUtf8("frame_setup"))
        self.layoutWidget2 = QtGui.QWidget(self.frame_setup)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 0, 724, 191))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout_setup = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_setup.setMargin(0)
        self.verticalLayout_setup.setObjectName(_fromUtf8("verticalLayout_setup"))
        self.gridLayout_setup_1 = QtGui.QGridLayout()
        self.gridLayout_setup_1.setContentsMargins(10, -1, 10, -1)
        self.gridLayout_setup_1.setObjectName(_fromUtf8("gridLayout_setup_1"))
        self.label_api_char = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_api_char.sizePolicy().hasHeightForWidth())
        self.label_api_char.setSizePolicy(sizePolicy)
        self.label_api_char.setMaximumSize(QtCore.QSize(42, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_api_char.setFont(font)
        self.label_api_char.setObjectName(_fromUtf8("label_api_char"))
        self.gridLayout_setup_1.addWidget(self.label_api_char, 3, 0, 1, 1)
        self.label_api_key = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_api_key.sizePolicy().hasHeightForWidth())
        self.label_api_key.setSizePolicy(sizePolicy)
        self.label_api_key.setMaximumSize(QtCore.QSize(42, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_api_key.setFont(font)
        self.label_api_key.setObjectName(_fromUtf8("label_api_key"))
        self.gridLayout_setup_1.addWidget(self.label_api_key, 1, 0, 1, 1)
        self.label_license = QtGui.QLabel(self.layoutWidget2)
        self.label_license.setEnabled(True)
        self.label_license.setMaximumSize(QtCore.QSize(55, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setBold(False)
        font.setWeight(50)
        self.label_license.setFont(font)
        self.label_license.setObjectName(_fromUtf8("label_license"))
        self.gridLayout_setup_1.addWidget(self.label_license, 5, 0, 1, 1)
        self.comboBox_char = QtGui.QComboBox(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_char.sizePolicy().hasHeightForWidth())
        self.comboBox_char.setSizePolicy(sizePolicy)
        self.comboBox_char.setMaximumSize(QtCore.QSize(200, 16777215))
        self.comboBox_char.setObjectName(_fromUtf8("comboBox_char"))
        self.gridLayout_setup_1.addWidget(self.comboBox_char, 3, 3, 1, 1)
        self.lineEdit_api_id = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_api_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_api_id.setSizePolicy(sizePolicy)
        self.lineEdit_api_id.setMinimumSize(QtCore.QSize(200, 0))
        self.lineEdit_api_id.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_api_id.setObjectName(_fromUtf8("lineEdit_api_id"))
        self.gridLayout_setup_1.addWidget(self.lineEdit_api_id, 0, 3, 1, 1)
        self.label_api_id = QtGui.QLabel(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_api_id.sizePolicy().hasHeightForWidth())
        self.label_api_id.setSizePolicy(sizePolicy)
        self.label_api_id.setMaximumSize(QtCore.QSize(42, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Armalite Rifle"))
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.label_api_id.setFont(font)
        self.label_api_id.setObjectName(_fromUtf8("label_api_id"))
        self.gridLayout_setup_1.addWidget(self.label_api_id, 0, 0, 1, 1)
        self.lineEdit_api_key = QtGui.QLineEdit(self.layoutWidget2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_api_key.sizePolicy().hasHeightForWidth())
        self.lineEdit_api_key.setSizePolicy(sizePolicy)
        self.lineEdit_api_key.setMinimumSize(QtCore.QSize(540, 0))
        self.lineEdit_api_key.setMaximumSize(QtCore.QSize(200, 16777215))
        self.lineEdit_api_key.setSizeIncrement(QtCore.QSize(2, 0))
        self.lineEdit_api_key.setObjectName(_fromUtf8("lineEdit_api_key"))
        self.gridLayout_setup_1.addWidget(self.lineEdit_api_key, 1, 3, 1, 1)
        self.lineEdit_license = QtGui.QLineEdit(self.layoutWidget2)
        self.lineEdit_license.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_license.sizePolicy().hasHeightForWidth())
        self.lineEdit_license.setSizePolicy(sizePolicy)
        self.lineEdit_license.setMinimumSize(QtCore.QSize(540, 0))
        self.lineEdit_license.setObjectName(_fromUtf8("lineEdit_license"))
        self.gridLayout_setup_1.addWidget(self.lineEdit_license, 5, 3, 1, 1)
        self.pushButton_api_save = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_api_save.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_api_save.sizePolicy().hasHeightForWidth())
        self.pushButton_api_save.setSizePolicy(sizePolicy)
        self.pushButton_api_save.setMaximumSize(QtCore.QSize(95, 25))
        self.pushButton_api_save.setObjectName(_fromUtf8("pushButton_api_save"))
        self.gridLayout_setup_1.addWidget(self.pushButton_api_save, 6, 0, 1, 1)
        self.pushButton_api_fetch = QtGui.QPushButton(self.layoutWidget2)
        self.pushButton_api_fetch.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_api_fetch.sizePolicy().hasHeightForWidth())
        self.pushButton_api_fetch.setSizePolicy(sizePolicy)
        self.pushButton_api_fetch.setMaximumSize(QtCore.QSize(95, 25))
        self.pushButton_api_fetch.setObjectName(_fromUtf8("pushButton_api_fetch"))
        self.gridLayout_setup_1.addWidget(self.pushButton_api_fetch, 2, 0, 1, 1)
        self.verticalLayout_setup.addLayout(self.gridLayout_setup_1)
        self.gridLayout_setup.addWidget(self.frame_setup, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_setup, _fromUtf8(""))
        self.verticalLayout_2.addWidget(self.tabWidget)

        self.retranslateUi(Trader)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Trader)

    def retranslateUi(self, Trader):
        Trader.setProperty("Name", _translate("Trader", "Form", None))
        self.checkBox_buy.setToolTip(_translate("Trader", "Force new data to act as a purchase.", None))
        self.checkBox_buy.setText(_translate("Trader", "Buy", None))
        self.checkBox_sell.setToolTip(_translate("Trader", "Force new data to act as a sale.", None))
        self.checkBox_sell.setText(_translate("Trader", "Sell", None))
        self.label_type.setToolTip(_translate("Trader", "BUY or SELL is based on detected clipboard data unless forced by you.", None))
        self.label_type.setText(_translate("Trader", "---", None))
        self.label_value.setToolTip(_translate("Trader", "Your clipboard will automatically update with this value", None))
        self.label_value.setText(_translate("Trader", "ISK", None))
        self.label_percent.setToolTip(_translate("Trader", "Percentage difference between your last order data and market data from your clipboard.", None))
        self.label_percent.setText(_translate("Trader", "%", None))
        self.label_pixmap.setToolTip(_translate("Trader", "Color based on thresholds. Red=large, Yellow=medium, Green=small. White=Equality, Black=Ignored.", None))
        self.label_pixmap.setText(_translate("Trader", "Updated", None))
        self.label_export_sell.setToolTip(_translate("Trader", "Cheapest price for sale on the market.", None))
        self.label_export_sell.setText(_translate("Trader", "Export Sell", None))
        self.label_export_buy.setToolTip(_translate("Trader", "Most expensive buy order on the market.", None))
        self.label_export_buy.setText(_translate("Trader", "Export Buy", None))
        self.label_export_diff.setToolTip(_translate("Trader", "ISK difference between your order and market selection.", None))
        self.label_export_diff.setText(_translate("Trader", "Diff", None))
        self.label_export_percent.setToolTip(_translate("Trader", "Percentage difference between your order and market selection.", None))
        self.label_export_percent.setText(_translate("Trader", "%", None))
        self.label_item.setText(_translate("Trader", "Item", None))
        self.button_manual.setText(_translate("Trader", "M", None))
        self.label_m_buy_low_icon.setToolTip(_translate("Trader", "Up arrow means clipboard is above your cheapest purchase price.", None))
        self.label_m_sell_low_icon.setToolTip(_translate("Trader", "Up arrow means clipboard is higher than your cheapest sale.", None))
        self.label_m_sell_high_percent.setToolTip(_translate("Trader", "Clipboard value is this much higher than your best sales price for this item. (negative indicates clipboard is below your highest sales price)", None))
        self.label_m_sell_high_percent.setText(_translate("Trader", "%", None))
        self.label_m_buy_fixed.setText(_translate("Trader", "BUY", None))
        self.label_m_buy_high.setToolTip(_translate("Trader", "Up arrow means clipboard is more than your highest purchase price.", None))
        self.label_m_buy_high.setText(_translate("Trader", "HIGH", None))
        self.label_m_buy_low.setToolTip(_translate("Trader", "The best bargin you\'ve bought this item for, based on your transactions.", None))
        self.label_m_buy_low.setText(_translate("Trader", "LOW", None))
        self.label_m_sell_high.setToolTip(_translate("Trader", "Your highest sales price for this item, based on your transactions.", None))
        self.label_m_sell_high.setText(_translate("Trader", "HIGH", None))
        self.label_m_buy_high_percent.setToolTip(_translate("Trader", "Clipboard value is higher than the most you\'ve paid to buy this item. (negative indicates clipboard is below your most expensive purchase of this item)", None))
        self.label_m_buy_high_percent.setText(_translate("Trader", "%", None))
        self.label_m_sell_low.setToolTip(_translate("Trader", "The cheapest you\'ve sold this item for, based on your transactions.", None))
        self.label_m_sell_low.setText(_translate("Trader", "LOW", None))
        self.label_m_sell_fixed.setText(_translate("Trader", "SELL", None))
        self.label_m_sell_low_percent.setToolTip(_translate("Trader", "Difference from clipboard value to your lowest sales price.", None))
        self.label_m_sell_low_percent.setText(_translate("Trader", "%", None))
        self.label_m_buy_low_percent.setToolTip(_translate("Trader", "Clipboard value is this much higher than your lowest purchase price. (negative indicates clipboard is even cheaper.", None))
        self.label_m_buy_low_percent.setText(_translate("Trader", "%", None))
        self.label_m_sell_high_icon.setToolTip(_translate("Trader", "Up arrow means clipboard is above your highest sale.", None))
        self.label_m_buy_high_icon.setToolTip(_translate("Trader", "Up arrow means clipboard is more than you\'ve ever paid.", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_trade), _translate("Trader", "Trade", None))
        self.lineEdit.setToolTip(_translate("Trader", "Your clipboard is automatically updated with the value shown here.", None))
        self.pushButton_7.setText(_translate("Trader", "7", None))
        self.pushButton_8.setText(_translate("Trader", "8", None))
        self.pushButton_9.setText(_translate("Trader", "9", None))
        self.pushButton_divide.setText(_translate("Trader", "/", None))
        self.pushButton_000.setText(_translate("Trader", "000", None))
        self.pushButton_4.setText(_translate("Trader", "4", None))
        self.pushButton_5.setText(_translate("Trader", "5", None))
        self.pushButton_6.setText(_translate("Trader", "6", None))
        self.pushButton_x.setText(_translate("Trader", "x", None))
        self.pushButton_99.setText(_translate("Trader", ".99", None))
        self.pushButton_1.setText(_translate("Trader", "1", None))
        self.pushButton_2.setText(_translate("Trader", "2", None))
        self.pushButton_3.setText(_translate("Trader", "3", None))
        self.pushButton_minus.setText(_translate("Trader", "-", None))
        self.pushButton_01.setText(_translate("Trader", ".01", None))
        self.pushButton_0.setText(_translate("Trader", "0", None))
        self.pushButton_dot.setText(_translate("Trader", ".", None))
        self.pushButton_equal.setText(_translate("Trader", "=", None))
        self.pushButton_plus.setText(_translate("Trader", "+", None))
        self.pushButton_C.setToolTip(_translate("Trader", "Clear", None))
        self.pushButton_C.setText(_translate("Trader", "C", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_calc), _translate("Trader", "Calculator", None))
        self.label_blueprint.setText(_translate("Trader", "Blueprint", None))
        self.label_cost.setText(_translate("Trader", "Cost", None))
        self.label_cost_actual.setText(_translate("Trader", "TextLabel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_indy), _translate("Trader", "Industry", None))
        self.label_copyright.setText(_translate("Trader", "Copyright", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_info), _translate("Trader", "Info", None))
        self.label_trade_green.setToolTip(_translate("Trader", "Changes to orders less than this percent will show green.", None))
        self.label_trade_green.setText(_translate("Trader", "Trade Green Below %", None))
        self.label_export_green.setToolTip(_translate("Trader", "Differences between the highest buy and the lowest sell in market exports show green when the gap is larger than this.", None))
        self.label_export_green.setText(_translate("Trader", "Export Green Above %", None))
        self.label_trade_yellow.setToolTip(_translate("Trader", "Changes to orders less than this percent will show yellow. Any less than this will be red.", None))
        self.label_trade_yellow.setText(_translate("Trader", "Trade Yellow Below %", None))
        self.label_export_yellow.setToolTip(_translate("Trader", "Differences between the highest buy and the lowest sell in market exports show yellow when the gap is larger than this. Any smaller gap will be red.", None))
        self.label_export_yellow.setText(_translate("Trader", "Export Yellow Above %", None))
        self.label_export_path.setText(_translate("Trader", "Export Path", None))
        self.label_api_ttl.setToolTip(_translate("Trader", "How long to cache api market data before fetching again. You can only update orders once every 5 minutes, so anything less than 300 is probably too often.", None))
        self.label_api_ttl.setText(_translate("Trader", "Api TTL", None))
        self.label_save_path.setText(_translate("Trader", "Save Path", None))
        self.label_pref_cached_static.setText(_translate("Trader", "Cached:", None))
        self.label_pref_cached.setText(_translate("Trader", "0", None))
        self.pushButton_pref_clear.setText(_translate("Trader", "Clear", None))
        self.pushButton_pref_save.setText(_translate("Trader", "Save", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_pref), _translate("Trader", "Prefs", None))
        self.label_api_char.setToolTip(_translate("Trader", "The character you will be using for trading.", None))
        self.label_api_char.setText(_translate("Trader", "Char", None))
        self.label_api_key.setToolTip(_translate("Trader", "The key field of your eve api key.", None))
        self.label_api_key.setText(_translate("Trader", "Key", None))
        self.label_license.setToolTip(_translate("Trader", "A license key is required to enable all features of this app. This field has nothing to do with your eve api key.", None))
        self.label_license.setText(_translate("Trader", "License", None))
        self.comboBox_char.setToolTip(_translate("Trader", "Select the name of your trading character here.", None))
        self.lineEdit_api_id.setToolTip(_translate("Trader", "Enter your eve api id here. (the shorter one)", None))
        self.label_api_id.setToolTip(_translate("Trader", "The ID field of your eve api key.", None))
        self.label_api_id.setText(_translate("Trader", "ID", None))
        self.lineEdit_api_key.setToolTip(_translate("Trader", "Enter your eve api key here. (the longer one)", None))
        self.lineEdit_license.setToolTip(_translate("Trader", "Entry your license key here to enable all features.", None))
        self.pushButton_api_save.setToolTip(_translate("Trader", "Push this button to save everything on this page after you fetch the characters, select your trading character, and enter a license key.", None))
        self.pushButton_api_save.setText(_translate("Trader", "Save", None))
        self.pushButton_api_fetch.setToolTip(_translate("Trader", "After entering the ID and Key, push the Fetch button to validate the key and retrieve a list of available characters.", None))
        self.pushButton_api_fetch.setText(_translate("Trader", "Fetch", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_setup), _translate("Trader", "Setup", None))

if __name__ == '__main__':
    import sys
    app = QtGui.QApplication(sys.argv)
    win = Ui_Trader()
    win.setupUi(win)
    win.retranslateUi(win)
    win.show()
    sys.exit(app.exec_())

